### ISSUE TITLE
Create a unified script

### ISSUE THREAD

**Issue by bbakernoaa** [NOAA-CSL/MELODIES-MONET#1]
We need to create a unified script.  One of the things that I am thinking about is a yaml file used to be a control file. An example could be something like this

```yaml
model: CMAQ
aeronet:
    use_aeronet: True
    paired_filename: aeronet_cmaq_combined_file.nc
    radius_of_influence: 1e5
    plots:
        plots_basename: 'aeronet_cmaq_%Y%m%d_' 
        taylor_diagram: True
        bias_plots: False
        timeseries: True
        giorgi_regional: False
        epa_regions: True
    stats:
        - rmse: True
        - mse: True
        - ioa: True
airnow:
    use_airnow: True
    paired_filename: aeronet_cmaq_combined_file.nc
    radius_of_influence: 1e5
    plots:
        plots_basename: 'aeronet_cmaq_%Y%m%d_'
        taylor_diagram: True
        bias_plots: False
        timeseries: True
        giorgi_regional: False
        epa_regions: True
    stats:
        - rmse: True
        - mse: True
        - ioa: True
```

Let me know what you guys think.
